{% set name = "libxkbcommon" %}
{% set version = "1.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xkbcommon/{{ name }}/archive/xkbcommon-{{ version }}.tar.gz
  sha256: bb1543d956a5b962ee414174e9882c5d6fac3af9f95ebf48defb105151780ed1

build:
  number: 0
  skip: true  # [win or osx]
  missing_dso_whitelist:
    - /lib/libc.so.6
  run_exports:
    - {{ pin_subpackage('libxkbcommon') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - m4
    - bison
    - cmake
    - pkg-config
  host:
    - xorg-libxau
    - libxcb
    - xorg-xproto
    - xcb-proto
    - pthread-stubs
    - libxml2-devel
  run:
    - xkeyboard-config

test:
  commands:
    - test -f "${PREFIX}/lib/libxkbcommon${SHLIB_EXT}"
    - xkbcli --help

about:
  home: https://github.com/xkbcommon/libxkbcommon
  license: MIT/X11 Derivative
  license_family: MIT
  license_file: LICENSE
  summary: keymap handling library for toolkits and window systems
  description: |
    libxkbcommon is a keyboard keymap compiler and support library which
    processes a reduced subset of keymaps as defined by the XKB (X Keyboard
    Extension) specification.
  doc_url: https://xkbcommon.org/
  dev_url: https://github.com/xkbcommon/libxkbcommon

extra:
  recipe-maintainers:
    - scopatz
    - hmaarrfk
