schema_version: 1

context:
  version: "1.13.2"

package:
  name: libxkbcommon
  version: ${{ version }}

source:
  url: https://github.com/xkbcommon/libxkbcommon/archive/xkbcommon-${{ version }}.tar.gz
  sha256: acc4d5f7c3cbba5f9f8d08d8bdbeede84ecede46792f47929aa9321873385528

build:
  number: 1
  skip: win or osx
  dynamic_linking:
    missing_dso_allowlist:
      - /lib/libc.so.6

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - meson
    - ninja
    - m4
    - bison
    - cmake
    - pkg-config
  host:
    - xorg-libxau
    - libxcb
    - xorg-xproto
    - xcb-proto
    - pthread-stubs
    - libxml2-devel
    - xkeyboard-config
  run:
    - xkeyboard-config
  run_exports:
    - ${{ pin_subpackage('libxkbcommon') }}

tests:
  - script:
      - test -f "${PREFIX}/lib/libxkbcommon${SHLIB_EXT}"
      - xkbcli --help

about:
  license: MIT AND MIT-open-group AND HPND AND HPND-sell-variant AND ISC AND LicenseRef-digital-equipment-corporation
  license_file:
    - LICENSE
    # TODO: Remove ISC_LICENSE.txt and this entry once
    # https://github.com/xkbcommon/libxkbcommon/pull/1077 is merged and included in a source release.
    - ISC_LICENSE.txt
  summary: keymap handling library for toolkits and window systems
  description: |
    libxkbcommon is a keyboard keymap compiler and support library which
    processes a reduced subset of keymaps as defined by the XKB (X Keyboard
    Extension) specification.
  homepage: https://github.com/xkbcommon/libxkbcommon
  repository: https://github.com/xkbcommon/libxkbcommon
  documentation: https://xkbcommon.org/

extra:
  recipe-maintainers:
    - scopatz
    - hmaarrfk
    - ytausch
